"""
This is a setup.py script generated by py2applet

This script is still needed since the latest version of py2app still doesn't enable using pyproject.toml, hmph.
"""

from setuptools import setup

APP = ['taskbridgeapp/gui/TaskBridge.py']
DATA_FILES = [
    ('taskbridgeapp/gui/assets', [
        'taskbridgeapp/gui/assets/bridge_animated_black.gif',
        'taskbridgeapp/gui/assets/bridge_animated_white.gif',
        'taskbridgeapp/gui/assets/bridge_black.png',
        'taskbridgeapp/gui/assets/bridge_white.png',
        'taskbridgeapp/gui/assets/refresh.png',
        'taskbridgeapp/gui/assets/TaskBridge.png',
        'taskbridgeapp/gui/assets/trash.png'
        ]
     )
]
OPTIONS = {
    "iconfile": "taskbridgeapp/gui/assets/TaskBridge.icns",
    'plist': {'LSUIElement': True}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
